//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafeProgramming.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cardholderUsers
    {
        public int id { get; set; }
        public string cardholderName { get; set; }
        public string cardNumber { get; set; }
        public string expDate { get; set; }
        public string cvc { get; set; }
    }
}
